# Thème du site
theme: jekyll-theme-cayman

# Titre du site (affiché dans l’onglet du navigateur)
title: Analyses de données et métabarcodes par Flora Larreur, M1 MFA, UBO Brest

# Description du site (pour moteurs de recherche)
description: Etudiante en Master 1 de micobiologie à l’Université de Bretagne Occidentale, je présente dès à présent sur ce site, mes travaux d’analyse de données métabarcodes.
